# Generated by Django 5.1.7 on 2025-03-28 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='zip',
            field=models.CharField(default='000000', max_length=10),
            preserve_default=False,
        ),
    ]
